Workflow: Build Test: Debug cloning and fix grepping

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -29,8 +29,13 @@ jobs:
         run: |
           set -x
           cd /home/frappe/frappe-bench
-          git clone https://rtbot:${{ secrets.RTBOT_TOKEN }}@github.com/${{ github.repository }} -b ${{ github.head_ref || github.ref_name }} app_repo
-          DEPS=$(grep -A 10 'required_apps' app_repo/*/hooks.py | grep -Po "'\K[^']+(?=')")
+          git clone https://rtbot:${{ secrets.RTBOT_TOKEN }}@github.com/${{ github.event.pull_request.head.repo.full_name }} -b ${{ github.event.pull_request.head.ref }} app_repo \
+            || (echo "❌ Git clone failed — check if branch or repo exists" && exit 1)
+          if [ ! -d "app_repo" ]; then
+            echo "❌ The repo 'app_repo' was not cloned correctly."
+            exit 1
+          fi
+          DEPS=$(grep -Po "(?<=required_apps\s*=\s*\[)[^]]+" app_repo/*/hooks.py | tr -d '"' | tr -d "'" | tr ',' '\n' | awk '{$1=$1};1')
           rm -rf app_repo
           for dep in $DEPS; do
             echo "Getting dependent app: $dep"
